name: Create and publish package

on:
  push:
    tags:
      - '*'

jobs:
  pre-build-checks:
    name: Pre-build checks
    uses: ./.github/workflows/tests.yaml

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: pre-build-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade build

      - name: Build packages
        run: python -m build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages-${{ github.ref_name }}
          path: dist/*

  pypi-release:
    name: Upload packages to PyPi
    needs: build
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade twine

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages-${{ github.ref_name }}
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create release on Github
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get packages
        uses: actions/download-artifact@v3
        with:
          name: packages-${{ github.ref_name }}
          path: dist/

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Summary:
              - TODO
          draft: true
          artifacts: dist/*