name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install -r test_requirements.txt

      - name: Run unittests
        run: python -m pytest --cov-fail-under=90

      - name: Verify dependencies
        run: python -m safety check

      - name: Verify code style
        run: python -m ruff check

      - name: Verify type annotations
        run: python -m mypy src/
